<?php 
if ($users->count() > 0) { ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>name</th>
            <th>description</th>
            <th>tag</th>
            <th>price</th>
            <th>stock</th>
        </tr>
        </thead>
        <tfoot>
            <h1>
                Products
            </h1>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->description ?></td>
                <td><?php echo $user->tag ?></td>
                <td><?php echo $user->price ?></td>
                <td><?php echo $user->stock ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php  //echo $this->tag->linkTo(["blog/index", "Go to blog "]);
     }?>
     <?php echo $this->tag->linkTo(
    'orders/addorder',
    'Add your orders');
?><br>
<br>
  <?php echo $this->tag->linkTo(
    'product',
    'go back');
?><br><br>
 <?php echo $this->tag->linkTo(
    'orders/vieworder',
    'view orders');
?>
